{% set name = "pyhf" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 175d5e69b0c73d161b7601c1ae158d4ddb3745c0eaea4c0d295f10cdac9ef9b4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pyhf = pyhf.cli:cli

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.13.0
    - hatch-vcs >=0.3.0
  run:
    - iminuit
    - jax
    - matplotlib
    - pytorch
    - tensorflow
    - tensorflow-probability
    - uproot
    - python >=3.7
    - scipy >=1.2.0
    - click >=8.0.0
    - tqdm >=4.56.0
    - jsonschema >=4.15.0
    - jsonpatch >=1.15
    - pyyaml >=5.1
    - importlib_resources >=1.4.0   # python < 3.9
    - typing_extensions >=3.7.4.3   # python < 3.8
    - numpy  # compatible versions controlled through scipy

test:
  imports:
    - pyhf
  commands:
    - pyhf --version

about:
  home: https://github.com/scikit-hep/pyhf
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: pure-Python HistFactory implementation

  description: |
    The HistFactory p.d.f. template [CERN-OPEN-2012-016] is per-se independent
    of its implementation in ROOT and sometimes, it's useful to be able to run
    statistical analysis outside of ROOT, RooFit, RooStats framework.

    This repo is a pure-python implementation of that statistical model for
    multi-bin histogram-based analysis and its interval estimation is based on
    the asymptotic formulas of "Asymptotic formulae for likelihood-based tests
    of new physics" [arXiv:1007.1727]. The aim is also to support modern
    computational graph libraries such as PyTorch and TensorFlow in order to
    make use of features such as autodifferentiation and GPU acceleration.
  doc_url: https://pyhf.readthedocs.io/
  dev_url: https://github.com/scikit-hep/pyhf

extra:
  recipe-maintainers:
    - matthewfeickert
    - lukasheinrich
    - kratsg
