{% set name = "pyhf" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc2923de6f0e90bedc7bd045a1efd70fe576dfe03ba7fa54a1f3ddeba192cbae

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pyhf = pyhf.cli:cli

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
  run:
    - python >=3.7
    - scipy >=1.4.0
    - click >=7.0
    - tqdm >=4.56
    - jsonschema >=3.2.0
    - jsonpatch >=1.23
    - pyyaml >=5.1

test:
  imports:
    - pyhf
  commands:
    - pyhf --version

about:
  home: https://github.com/scikit-hep/pyhf
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: pure-Python HistFactory implementation

  description: |
    The HistFactory p.d.f. template [CERN-OPEN-2012-016] is per-se independent
    of its implementation in ROOT and sometimes, it's useful to be able to run
    statistical analysis outside of ROOT, RooFit, RooStats framework.

    This repo is a pure-python implementation of that statistical model for
    multi-bin histogram-based analysis and its interval estimation is based on
    the asymptotic formulas of "Asymptotic formulae for likelihood-based tests
    of new physics" [arXiv:1007.1727]. The aim is also to support modern
    computational graph libraries such as PyTorch and TensorFlow in order to
    make use of features such as autodifferentiation and GPU acceleration.
  doc_url: https://pyhf.readthedocs.io/
  dev_url: https://github.com/scikit-hep/pyhf

extra:
  recipe-maintainers:
    - matthewfeickert
    - lukasheinrich
    - kratsg
