conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
bot:
  # https://conda-forge.org/docs/maintainer/conda_forge_yml.html#bot
  inspection: hint
conda_build:
  pkg_format: '2'
